server:
  port: 8001
spring:
  application:
    name: nacos-provider-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.100:8848
        service: ${spring.application.name}-${server.port}


#暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'